# typed: false
# frozen_string_literal: true

# This file was generated by the Gemini CLI.
# It is a Homebrew formula for the MakeMeGo application.
#
# To make this formula work, you will need to:
# 1. Push your project to a GitHub repository.
# 2. Create a new release on GitHub.
# 3. Update the `url` and `sha256` fields below with the URL and checksum of the release archive.
#
# You can then install the formula locally with:
#   brew install --build-from-source ./Formula/makemego.rb
#
# For more information, see: https://docs.brew.sh/Formula-Cookbook

class Mm < Formula
  desc "Interactively select and run make targets"
  homepage "https://github.com/YOUR_USERNAME/MakeMeGo" # TODO: Update with your GitHub repository URL
  url "https://github.com/YOUR_USERNAME/MakeMeGo/archive/refs/tags/v0.1.0.tar.gz" # TODO: Update with the URL of your release archive
  sha256 "0000000000000000000000000000000000000000000000000000000000000000" # TODO: Update with the SHA256 checksum of your release archive

  depends_on "go" => :build
  depends_on "fzf"

  def install
    system "go", "build", "-o", "mm", "./cmd/makemego"
    bin.install "mm"

    # Install shell integration
    pkgshare.install "misc/mm.bash"
    pkgshare.install "misc/mm.zsh"
    pkgshare.install "misc/mm.fish"
  end

  def caveats
    <<~EOS
      To enable shell integration, run the following command for your shell:

      Bash:
        echo "source #{opt_pkgshare}/mm.bash" >> ~/.bashrc

      Zsh:
        echo "source #{opt_pkgshare}/mm.zsh" >> ~/.zshrc

      Fish:
        echo "source #{opt_pkgshare}/mm.fish" >> ~/.config/fish/config.fish
    EOS
  end

  test do
    assert_match "Usage: mm", shell_output("#{bin}/mm -h")
  end
end
